---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: stage
spec:
  imageRepositoryRef:
    name: kbot
  policy:
    semver:
      range: 'v1.0.3-d435be0-linux-amd64'
