---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: prod
spec:
  imageRepositoryRef:
    name: kbot
  policy:
    semver:
      range: 'v1.0.2-f67e572-linux-amd64'
