apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kbot-image
  policy:
    semver:
      range: ">=1.0.2"
