---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: dev
spec:
  imageRepositoryRef:
    name: kbot
  policy:
    semver:
      range: 'v1.0.2-9215d76-linux-amd64'
    alphabetical:
      order: asc
