---
apiVersion: v1
data:
  token: Njk1ODA1MTcxOTpBQUU0SW40N3RaQkxncnZCSWNPZ0ZOYUJIZkRHR191LXN2TQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: kbot
  namespace: dev
  annotations:
    meta.helm.sh/release-name: kbot
    meta.helm.sh/release-namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: kbot
    helm.toolkit.fluxcd.io/namespace: dev