---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: qa
spec:
  imageRepositoryRef:
    name: kbot
  filterTags:
    pattern: '^(v?1\.[0-9]+\.[0-9]+(?:-[a-f0-9]{7})?)$'
    extract: '$1'
  policy:
    semver:
      range: "v1.0.2-ff646e2" 
