---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: qa
spec:
  imageRepositoryRef:
    name: kbot
  filterTags:
    pattern: '^(v1\.0\.2-9215d76)(?:-linux-amd64)?$'
    extract: '$1'
  policy:
    semver:
      range: 'sdfs'
    alphabetical:
      order: asc
