---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: qa
spec:
  imageRepositoryRef:
    name: kbot
  policy:
    semver:
      range: 'v1.0.5-8a2ebc5-linux-amd64'
