---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: qa
spec:
  imageRepositoryRef:
    name: kbot
  filterTags:
    pattern: '^(v?1\.[0-9]\.[0-9]{1,2})-[a-f0-9]+'
    extract: '$1'
  policy:
    semver:
      range: ">=1.0.0 <2.0.0" 
